//protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative grpc/employee.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: grpc/employee.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Employee struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Surname string `protobuf:"bytes,3,opt,name=surname,proto3" json:"surname,omitempty"`
}

func (x *Employee) Reset() {
	*x = Employee{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_employee_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Employee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee) ProtoMessage() {}

func (x *Employee) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_employee_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee.ProtoReflect.Descriptor instead.
func (*Employee) Descriptor() ([]byte, []int) {
	return file_grpc_employee_proto_rawDescGZIP(), []int{0}
}

func (x *Employee) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Employee) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Employee) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

type ResponseCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// if code if 4xx or 5xx then we have 'error'
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ResponseCode) Reset() {
	*x = ResponseCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_employee_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCode) ProtoMessage() {}

func (x *ResponseCode) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_employee_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCode.ProtoReflect.Descriptor instead.
func (*ResponseCode) Descriptor() ([]byte, []int) {
	return file_grpc_employee_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseCode) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResponseCode) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HoursWorked struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hours        float64       `protobuf:"fixed64,1,opt,name=hours,proto3" json:"hours,omitempty"`
	ResponseCode *ResponseCode `protobuf:"bytes,2,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
}

func (x *HoursWorked) Reset() {
	*x = HoursWorked{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_employee_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HoursWorked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoursWorked) ProtoMessage() {}

func (x *HoursWorked) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_employee_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoursWorked.ProtoReflect.Descriptor instead.
func (*HoursWorked) Descriptor() ([]byte, []int) {
	return file_grpc_employee_proto_rawDescGZIP(), []int{2}
}

func (x *HoursWorked) GetHours() float64 {
	if x != nil {
		return x.Hours
	}
	return 0
}

func (x *HoursWorked) GetResponseCode() *ResponseCode {
	if x != nil {
		return x.ResponseCode
	}
	return nil
}

type SalaryPH struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Salary       *Salary       `protobuf:"bytes,1,opt,name=salary,proto3" json:"salary,omitempty"`
	ResponseCode *ResponseCode `protobuf:"bytes,2,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
}

func (x *SalaryPH) Reset() {
	*x = SalaryPH{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_employee_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SalaryPH) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalaryPH) ProtoMessage() {}

func (x *SalaryPH) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_employee_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalaryPH.ProtoReflect.Descriptor instead.
func (*SalaryPH) Descriptor() ([]byte, []int) {
	return file_grpc_employee_proto_rawDescGZIP(), []int{3}
}

func (x *SalaryPH) GetSalary() *Salary {
	if x != nil {
		return x.Salary
	}
	return nil
}

func (x *SalaryPH) GetResponseCode() *ResponseCode {
	if x != nil {
		return x.ResponseCode
	}
	return nil
}

type Salary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dollars int64 `protobuf:"varint,1,opt,name=dollars,proto3" json:"dollars,omitempty"`
	Cents   int64 `protobuf:"varint,2,opt,name=cents,proto3" json:"cents,omitempty"`
}

func (x *Salary) Reset() {
	*x = Salary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_employee_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Salary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Salary) ProtoMessage() {}

func (x *Salary) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_employee_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Salary.ProtoReflect.Descriptor instead.
func (*Salary) Descriptor() ([]byte, []int) {
	return file_grpc_employee_proto_rawDescGZIP(), []int{4}
}

func (x *Salary) GetDollars() int64 {
	if x != nil {
		return x.Dollars
	}
	return 0
}

func (x *Salary) GetCents() int64 {
	if x != nil {
		return x.Cents
	}
	return 0
}

var File_grpc_employee_proto protoreflect.FileDescriptor

var file_grpc_employee_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x08, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x38, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x56, 0x0a, 0x0b, 0x48, 0x6f, 0x75,
	0x72, 0x73, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x6f, 0x75, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x68, 0x6f, 0x75, 0x72, 0x73, 0x12, 0x31,
	0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x22, 0x5e, 0x0a, 0x08, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x50, 0x48, 0x12, 0x1f, 0x0a,
	0x06, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e,
	0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x52, 0x06, 0x73, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x12, 0x31,
	0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x22, 0x38, 0x0a, 0x06, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x64,
	0x6f, 0x6c, 0x6c, 0x61, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x64, 0x6f,
	0x6c, 0x6c, 0x61, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x65, 0x6e, 0x74, 0x73, 0x32, 0xc7, 0x01, 0x0a, 0x12,
	0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c,
	0x65, 0x72, 0x12, 0x2c, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x53,
	0x68, 0x69, 0x66, 0x74, 0x12, 0x09, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x1a,
	0x0d, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x00,
	0x12, 0x2a, 0x0a, 0x0c, 0x45, 0x6e, 0x64, 0x57, 0x6f, 0x72, 0x6b, 0x53, 0x68, 0x69, 0x66, 0x74,
	0x12, 0x09, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x1a, 0x0d, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x64, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x12, 0x09,
	0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x1a, 0x0c, 0x2e, 0x48, 0x6f, 0x75, 0x72,
	0x73, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x64, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x50, 0x65, 0x72, 0x48, 0x6f, 0x75, 0x72, 0x12, 0x09, 0x2e,
	0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x1a, 0x09, 0x2e, 0x53, 0x61, 0x6c, 0x61, 0x72,
	0x79, 0x50, 0x48, 0x22, 0x00, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x69, 0x6e, 0x67, 0x30, 0x2d, 0x72, 0x6f, 0x6f, 0x74, 0x6b, 0x69,
	0x74, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2d, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2d, 0x6d,
	0x6e, 0x67, 0x6d, 0x6e, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_grpc_employee_proto_rawDescOnce sync.Once
	file_grpc_employee_proto_rawDescData = file_grpc_employee_proto_rawDesc
)

func file_grpc_employee_proto_rawDescGZIP() []byte {
	file_grpc_employee_proto_rawDescOnce.Do(func() {
		file_grpc_employee_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_employee_proto_rawDescData)
	})
	return file_grpc_employee_proto_rawDescData
}

var file_grpc_employee_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_grpc_employee_proto_goTypes = []interface{}{
	(*Employee)(nil),     // 0: Employee
	(*ResponseCode)(nil), // 1: ResponseCode
	(*HoursWorked)(nil),  // 2: HoursWorked
	(*SalaryPH)(nil),     // 3: SalaryPH
	(*Salary)(nil),       // 4: Salary
}
var file_grpc_employee_proto_depIdxs = []int32{
	1, // 0: HoursWorked.responseCode:type_name -> ResponseCode
	4, // 1: SalaryPH.salary:type_name -> Salary
	1, // 2: SalaryPH.responseCode:type_name -> ResponseCode
	0, // 3: EmployeeController.StartWorkShift:input_type -> Employee
	0, // 4: EmployeeController.EndWorkShift:input_type -> Employee
	0, // 5: EmployeeController.GetWorkedHours:input_type -> Employee
	0, // 6: EmployeeController.GetSalaryPerHour:input_type -> Employee
	1, // 7: EmployeeController.StartWorkShift:output_type -> ResponseCode
	1, // 8: EmployeeController.EndWorkShift:output_type -> ResponseCode
	2, // 9: EmployeeController.GetWorkedHours:output_type -> HoursWorked
	3, // 10: EmployeeController.GetSalaryPerHour:output_type -> SalaryPH
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_grpc_employee_proto_init() }
func file_grpc_employee_proto_init() {
	if File_grpc_employee_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_employee_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Employee); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_employee_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_employee_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HoursWorked); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_employee_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SalaryPH); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_employee_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Salary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_employee_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_employee_proto_goTypes,
		DependencyIndexes: file_grpc_employee_proto_depIdxs,
		MessageInfos:      file_grpc_employee_proto_msgTypes,
	}.Build()
	File_grpc_employee_proto = out.File
	file_grpc_employee_proto_rawDesc = nil
	file_grpc_employee_proto_goTypes = nil
	file_grpc_employee_proto_depIdxs = nil
}
